##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.1.0] date: [Fri Apr 26 11:23:21 CST 2024] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = stm32f767zi_freeRTOS_first_project


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build
FREERTOS_PLUS_TCP_DIR = ThirdParty/FreeRTOS-Plus-TCP/source

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32f7xx_it.c \
Core/Src/stm32f7xx_hal_msp.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c \
Core/Src/system_stm32f7xx.c \
Core/Src/syscalls.c \
Core/Src/stm32f7xx_hal_timebase_tim.c \
Core/Src/freertos.c \
ThirdParty/FreeRTOS/Source/croutine.c \
ThirdParty/FreeRTOS/Source/event_groups.c \
ThirdParty/FreeRTOS/Source/list.c \
ThirdParty/FreeRTOS/Source/queue.c \
ThirdParty/FreeRTOS/Source/stream_buffer.c \
ThirdParty/FreeRTOS/Source/tasks.c \
ThirdParty/FreeRTOS/Source/timers.c \
ThirdParty/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1/port.c \
ThirdParty/FreeRTOS/Source/portable/MemMang/heap_4.c \
ThirdParty/SEGGER/SystemView/Config/SEGGER_SYSVIEW_Config_FreeRTOS.c \
ThirdParty/SEGGER/SystemView/OS/SEGGER_SYSVIEW_FreeRTOS.c \
ThirdParty/SEGGER/SystemView/SEGGER/SEGGER_RTT_printf.c \
ThirdParty/SEGGER/SystemView/SEGGER/SEGGER_RTT.c \
ThirdParty/SEGGER/SystemView/SEGGER/SEGGER_SYSVIEW.c \
$(wildcard $(FREERTOS_PLUS_TCP_DIR)/*.c) \
$(FREERTOS_PLUS_TCP_DIR)/portable/NetworkInterface/STM32Fxx/NetworkInterface.c \
$(FREERTOS_PLUS_TCP_DIR)/portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.c \
$(FREERTOS_PLUS_TCP_DIR)/portable/NetworkInterface/Common/phyHandling.c \
$(FREERTOS_PLUS_TCP_DIR)/portable/BufferManagement/BufferAllocation_2.c \
Core/Src/ethernet_if.c \
Core/Src/stm32f7xx_timer_extension.c \
Core/Src/double_buffer_mem_manage.c \
Core/Src/encoder.c \
#ThirdParty/SEGGER/SystemView/SEGGER/syscalls/SEGGER_RTT_Syscalls_GCC.c \

# ASM sources
ASM_SOURCES =  \
startup_stm32f767xx.s \

# AMS sources with capital S
ASM_SOURCES_UPPERCASE =  \
ThirdParty/SEGGER/SystemView/SEGGER/SEGGER_RTT_ASM_ARMv7M.S \


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F767xx \
-DSTM32F7xx 

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F7xx_HAL_Driver/Inc \
-IDrivers/STM32F7xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F7xx/Include \
-IDrivers/CMSIS/Include \
-IThirdParty/FreeRTOS/Source/include \
-IThirdParty/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
-IThirdParty/SEGGER/SystemView/Config \
-IThirdParty/SEGGER/SystemView/OS \
-IThirdParty/SEGGER/SystemView/SEGGER \
-I$(FREERTOS_PLUS_TCP_DIR)/include \
-I$(FREERTOS_PLUS_TCP_DIR)/portable/Compiler/GCC \
-I$(FREERTOS_PLUS_TCP_DIR)/portable/NetworkInterface/include \
-I$(FREERTOS_PLUS_TCP_DIR)/portable/NetworkInterface/STM32Fxx

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F767ZITx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES_UPPERCASE:.S=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
vpath %.S $(sort $(dir $(ASM_SOURCES_UPPERCASE)))


$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
